apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Page déployée depuis GitHub avec ArgoCD</title>
    </head>
    <body>
      <h1>Page déployée depuis GitHub avec ArgoCD</h1>
      <p>Bienvenue dans le TP GitOps complet !</p>
      <p>Modification poussée sur GitHub puis synchronisée avec ArgoCD.</p>
    </body>
    </html>
